const { pool } = require('../config/database');
async function findActiveUser(id){ const [[u]]=await pool.query("SELECT u.id,u.nombre,u.estado,r.nombre rol FROM usuarios u INNER JOIN roles r ON r.id=u.rol_id WHERE u.id=? AND u.estado='activo' AND u.deleted_at IS NULL",[id]); return u||null; }
async function follow(seguidor_id,seguido_id){ const [r]=await pool.query('INSERT IGNORE INTO seguimientos (seguidor_id,seguido_id) VALUES (?,?)',[seguidor_id,seguido_id]); return r.affectedRows>0; }
async function unfollow(seguidor_id,seguido_id){ const [r]=await pool.query('DELETE FROM seguimientos WHERE seguidor_id=? AND seguido_id=?',[seguidor_id,seguido_id]); return r.affectedRows>0; }
async function isFollowing(seguidor_id,seguido_id){ if(!seguidor_id) return false; const [[r]]=await pool.query('SELECT id FROM seguimientos WHERE seguidor_id=? AND seguido_id=? LIMIT 1',[seguidor_id,seguido_id]); return Boolean(r); }
async function counts(userId){ const [[a]]=await pool.query('SELECT COUNT(*) total FROM seguimientos WHERE seguido_id=?',[userId]); const [[b]]=await pool.query('SELECT COUNT(*) total FROM seguimientos WHERE seguidor_id=?',[userId]); return {total_seguidores:Number(a.total||0),total_siguiendo:Number(b.total||0)}; }
async function followers(userId,{limit=20,offset=0}){ const [rows]=await pool.query(`SELECT u.id,u.nombre,r.nombre rol,s.created_at FROM seguimientos s INNER JOIN usuarios u ON u.id=s.seguidor_id INNER JOIN roles r ON r.id=u.rol_id WHERE s.seguido_id=? ORDER BY s.created_at DESC LIMIT ? OFFSET ?`,[userId,limit,offset]); return rows; }
async function following(userId,{limit=20,offset=0}){ const [rows]=await pool.query(`SELECT u.id,u.nombre,r.nombre rol,s.created_at FROM seguimientos s INNER JOIN usuarios u ON u.id=s.seguido_id INNER JOIN roles r ON r.id=u.rol_id WHERE s.seguidor_id=? ORDER BY s.created_at DESC LIMIT ? OFFSET ?`,[userId,limit,offset]); return rows; }
module.exports={findActiveUser,follow,unfollow,isFollowing,counts,followers,following};
