const { pool } = require('../config/database');
async function create({producto_id,comprador_id,pedido_id,estrellas,comentario}){ const [r]=await pool.query("INSERT INTO resenas (producto_id,comprador_id,pedido_id,estrellas,comentario,estado) VALUES (?,?,?,?,?,'aprobada')",[producto_id,comprador_id,pedido_id,estrellas,comentario||null]); return findById(r.insertId); }
async function findById(id){ const [r]=await pool.query('SELECT * FROM resenas WHERE id=? LIMIT 1',[id]); return r[0]||null; }
async function duplicate(productoId,compradorId,pedidoId){ const [[r]]=await pool.query('SELECT COUNT(*) total FROM resenas WHERE producto_id=? AND comprador_id=? AND pedido_id=?',[productoId,compradorId,pedidoId]); return r.total>0; }
async function listApproved(productoId){ const [r]=await pool.query(`SELECT r.id,r.producto_id,r.estrellas,r.comentario,r.created_at,u.nombre comprador_nombre FROM resenas r INNER JOIN usuarios u ON u.id=r.comprador_id WHERE r.producto_id=? AND r.estado='aprobada' ORDER BY r.created_at DESC`,[productoId]); return r; }
async function updateStatus(id,estado){ await pool.query('UPDATE resenas SET estado=? WHERE id=?',[estado,id]); return findById(id); }
async function productStats(productId){ const [[r]]=await pool.query("SELECT COALESCE(AVG(estrellas),0) promedio, COUNT(*) total FROM resenas WHERE producto_id=? AND estado='aprobada'",[productId]); return {promedio:Number(r.promedio), total:r.total}; }
async function storeStats(storeId){ const [[r]]=await pool.query(`SELECT COALESCE(AVG(r.estrellas),0) promedio, COUNT(*) total, COUNT(DISTINCT r.producto_id) productos FROM resenas r INNER JOIN productos p ON p.id=r.producto_id WHERE p.tienda_id=? AND r.estado='aprobada'`,[storeId]); return {promedio:Number(r.promedio), total:r.total, productos:r.productos}; }
module.exports={pool,create,findById,duplicate,listApproved,updateStatus,productStats,storeStats};
