import { api, token, updateStoredUser } from './api.js';
import { money, showMessage } from './ui.js';
import { UPLOADS_BASE_URL } from './config.js';

const page = location.pathname.split('/').pop() || 'admin.html';
const adminPages = new Set(['admin.html','admin-usuarios.html','admin-tiendas.html','admin-productos.html','admin-categorias.html','admin-pedidos.html','admin-pagos.html','admin-envios.html','admin-resenas.html','admin-comisiones.html','admin-notificaciones.html','admin-logs.html','admin-reportes.html']);
const state = { user:null };

function esc(v){return String(v ?? '').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function main(){return document.querySelector('main');}
function icon(name,cls='cc-icon'){return `<img class="${cls}" src="assets/icons/${name}" alt="">`;}
function imageUrl(v,fb='assets/icons/cc-product-card.svg'){ if(!v) return fb; const s=String(v); if(s.startsWith('/uploads')) return `${UPLOADS_BASE_URL}${s.replace('/uploads','')}`; if(s.startsWith('/')) return `${UPLOADS_BASE_URL}/${s.replace(/^\/+/, '')}`; return s; }
function chipClass(status){ status=String(status||'').toLowerCase(); if(['activo','activa','aprobado','aprobada','pagado','entregado','resuelto'].includes(status)) return 'blue'; if(['pendiente','en_revision','revisado','agotado'].includes(status)) return 'orange'; return 'neutral'; }
function norm(v){ return String(v||'pendiente').toLowerCase().replace(/\s+/g,'-').replace('bloqueado','baneado').replace('aprobados','aprobado').replace('aprobadas','aprobada').replace('rechazados','rechazado').replace('rechazadas','rechazada').replace('sin-stock','agotado'); }
function empty(iconName,title,text){ return `<section class="cc-card cc-empty-state"><img class="cc-icon-lg" src="assets/icons/${iconName}" alt=""><h2 class="text-2xl font-bold">${esc(title)}</h2><p class="cc-muted">${esc(text)}</p></section>`; }
function shell(title,iconName,chip,desc,action=''){ return `<div class="cc-section-title"><div><span class="cc-chip orange">${icon(iconName)} ${esc(chip)}</span><h1 class="text-4xl font-bold mt-3">${esc(title)}</h1><p class="cc-muted">${esc(desc)}</p></div>${action}</div>`; }
async function safe(path, fallback=null){ try{return await api.get(path);}catch(error){return {error, data:fallback};} }
async function postSafe(path,body){ return api.post(path,body); }
async function patchSafe(path,body){ return api.patch(path,body); }
async function delSafe(path){ return api.delete(path); }

async function adminSession(){
  if(!token()){ main()?.insertAdjacentHTML('afterbegin','<section class="cc-card cc-soft-warning mb-5"><b>Sesión administrativa requerida.</b><p>Inicia sesión como administrador para consultar datos reales.</p><a class="cc-btn mt-3" href="login.html">Ir a login</a></section>'); return null; }
  try{ const res=await api.get('/auth/me'); const user=res.data.user; updateStoredUser(user); if(user.rol==='comprador'){location.href='comprador.html';return null;} if(user.rol==='vendedor'){location.href='vendedor.html';return null;} if(user.rol!=='administrador') throw new Error('La sesión actual no corresponde a administrador.'); state.user=user; return user; }
  catch(error){ main()?.insertAdjacentHTML('afterbegin',`<section class="cc-card cc-soft-warning mb-5"><b>No se pudo validar administrador.</b><p>${esc(error.message)}</p><a class="cc-btn mt-3" href="login.html">Iniciar sesión</a></section>`); return null; }
}
function bindFilters(root=document){
  root.querySelectorAll('[data-admin-filter-group]').forEach(group=>{
    const key=group.dataset.adminFilterGroup;
    const selector=`[data-admin-item="${key}"]`;
    const apply=()=>{ const filter=group.querySelector('.active')?.dataset.filter || 'all'; const q=(root.querySelector(`[data-admin-search="${key}"]`)?.value||'').toLowerCase().trim(); let visible=0; const items=[...root.querySelectorAll(selector)]; items.forEach(item=>{ const st=item.dataset.status||''; const role=item.dataset.role||''; const text=(item.dataset.filterText||item.innerText||'').toLowerCase(); const byFilter=filter==='all'||st===filter||role===filter||text.includes(filter); const byQuery=!q||text.includes(q); const show=byFilter&&byQuery; item.classList.toggle('hidden',!show); if(show) visible++; }); root.querySelector(`[data-admin-empty="${key}"]`)?.classList.toggle('hidden',visible>0||!items.length); };
    group.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{group.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');apply();}));
    root.querySelector(`[data-admin-search="${key}"]`)?.addEventListener('input',apply);
    apply();
  });
}
function filters(key,items,search='Buscar'){return `<section class="cc-card mb-5"><div class="cc-module-filters" data-admin-filter-group="${key}">${items.map((it,i)=>`<button class="cc-filter-pill ${i===0?'active':''}" data-filter="${esc(it[0])}" type="button">${esc(it[1])}</button>`).join('')}</div>${search?`<label class="cc-label mt-4">${esc(search)}<input class="cc-input" data-admin-search="${key}" placeholder="Buscar en datos reales"></label>`:''}</section>`;}

async function dashboard(user){
  const [statsRes, usersRes, ordersRes, logsRes, prodReports, userReports, returnsRes, productsRes, catsRes, notifCount]=await Promise.all([safe('/admin/dashboard-stats'),safe('/admin/users'),safe('/admin/orders'),safe('/admin/logs'),safe('/admin/reports/products'),safe('/admin/reports/users'),safe('/admin/returns'),safe('/products?limit=20'),safe('/categories'),safe('/notifications/unread-count')]);
  const stats=statsRes.data?.stats||{}; const cards=[['Usuarios',stats.total_compradores+stats.total_vendedores+stats.total_administradores||usersRes.data?.users?.length||0,'admin-usuarios.html'],['Tiendas',stats.total_tiendas||0,'admin-tiendas.html'],['Productos',stats.total_productos||productsRes.data?.products?.length||0,'admin-productos.html'],['Pedidos',stats.total_pedidos||ordersRes.data?.orders?.length||0,'admin-pedidos.html'],['Comisiones',money(stats.comisiones_totales||0),'admin-comisiones.html'],['Logs',logsRes.data?.logs?.length||0,'admin-logs.html'],['Reportes',Number(stats.reportes_productos_pendientes||0)+Number(stats.reportes_usuarios_pendientes||0),'admin-reportes.html'],['Notificaciones',notifCount.data?.unread_count||0,'admin-notificaciones.html']];
  const section=main().querySelector('section.grid.gap-5')||main();
  section.insertAdjacentHTML('afterbegin',`<section class="cc-card cc-api-summary"><h2 class="text-2xl font-bold">Panel real de ${esc(user.nombre||'administrador')}</h2><p class="cc-muted">Estadísticas administrativas conectadas a la API.</p></section><section class="cc-grid cols-4">${cards.map(c=>`<a class="cc-card cc-metric-card" href="${c[2]}"><b>${c[0]}</b><strong>${c[1]}</strong><span>API real</span></a>`).join('')}</section>`);
}
async function usersPage(){ const res=await safe('/admin/users'); const users=res.data?.users||[]; main().innerHTML=shell('Usuarios','cc-users-management.svg','Administración','Usuarios reales registrados en CommerCity.')+filters('users',[['all','Todos'],['comprador','Compradores'],['vendedor','Vendedores'],['administrador','Administradores'],['activo','Activos'],['baneado','Bloqueados']],'Buscar usuario')+`<section class="cc-table-wrap"><table class="cc-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Registro</th><th>Acciones</th></tr></thead><tbody>${users.map(u=>`<tr data-admin-item="users" data-role="${esc(u.rol)}" data-status="${esc(norm(u.estado))}" data-filter-text="${esc(`${u.nombre} ${u.correo} ${u.rol} ${u.estado}`)}"><td>${esc(u.nombre)}</td><td>${esc(u.correo)}</td><td>${esc(u.rol)}</td><td><span class="cc-chip ${chipClass(u.estado)}">${esc(u.estado)}</span></td><td>${esc(u.created_at||'')}</td><td><div class="cc-mini-actions"><button type="button" data-user-status="${esc(u.id)}" data-next-status="${norm(u.estado)==='activo'?'baneado':'activo'}">${norm(u.estado)==='activo'?'Bloquear':'Activar'}</button><button type="button" data-visual-action="Detalle de usuario preparado">Ver usuario</button></div></td></tr>`).join('')}</tbody></table></section>${users.length?'':empty('cc-users-management.svg','Sin usuarios reales.','La API no devolvió usuarios.')}`; bindFilters(main()); }
async function storesPage(){ const res=await safe('/admin/search?q=tienda'); const stores=res.data?.results?.tiendas||[]; main().innerHTML=shell('Tiendas','cc-store-shopping-bag.svg','Tiendas','Listado obtenido desde búsqueda administrativa real.','')+filters('stores',[['all','Todas'],['activa','Activas'],['pendiente','Pendientes'],['pausada','Suspendidas']],'Buscar tienda')+`<section class="cc-grid cols-2">${stores.map(s=>`<article class="cc-card" data-admin-item="stores" data-status="${esc(norm(s.estado))}" data-filter-text="${esc(`${s.nombre} ${s.estado} ${s.slug}`)}"><span class="cc-chip ${chipClass(s.estado)}">${esc(s.estado||'estado')}</span><h2>${esc(s.nombre)}</h2><p class="cc-muted">Slug: ${esc(s.slug||'no disponible')} · Reputación: ${esc(s.reputacion_promedio||0)}</p><div class="cc-card-actions-row"><a class="cc-btn outline" href="tienda.html?id=${esc(s.id)}">Ver tienda</a><button class="cc-btn" type="button" data-store-action="${esc(s.id)}" data-action="activate">Activar</button><button class="cc-btn secondary" type="button" data-store-action="${esc(s.id)}" data-action="pause">Suspender</button></div></article>`).join('')}</section>${stores.length?'':empty('cc-store-shopping-bag.svg','Listado directo de tiendas pendiente.','No existe GET /admin/stores; se usa /admin/search?q=tienda como fuente disponible.')}`; bindFilters(main()); }
async function productsPage(){ const [productsRes,reportsRes]=await Promise.all([safe('/products?limit=50'),safe('/admin/reports/products')]); const products=productsRes.data?.products||[]; const reports=reportsRes.data?.reports||[]; const reported=new Set(reports.map(r=>String(r.producto_id||r.product_id))); main().innerHTML=shell('Productos','cc-products-management.svg','Catálogo','Productos reales y reportes administrativos.')+filters('products',[['all','Todos'],['activo','Activos'],['oculto','Pausados'],['agotado','Sin stock'],['reportado','Reportados']],'Buscar producto')+`<section class="cc-table-wrap"><table class="cc-table"><thead><tr><th>Producto</th><th>Tienda</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${products.map(p=>{const id=p.id||p.producto_id; const st=reported.has(String(id))?'reportado':norm(p.estado||(Number(p.stock)===0?'agotado':'activo')); return `<tr data-admin-item="products" data-status="${esc(st)}" data-filter-text="${esc(`${p.nombre} ${p.tienda_nombre} ${p.categoria_nombre} ${st}`)}"><td><span class="cc-table-product"><img class="cc-icon" src="${esc(imageUrl(p.imagen_url))}" alt="">${esc(p.nombre)}</span></td><td>${esc(p.tienda_nombre||'')}</td><td>${esc(p.categoria_nombre||'')}</td><td>${money(p.precio_final||p.precio||0)}</td><td>${esc(p.stock??0)}</td><td><span class="cc-chip ${chipClass(st)}">${esc(st)}</span></td><td><div class="cc-mini-actions"><a href="producto-detalle.html?id=${esc(id)}">Ver</a><button type="button" data-product-visibility="${esc(id)}" data-next-status="${st==='activo'?'oculto':'activo'}">${st==='activo'?'Ocultar':'Activar'}</button><button type="button" data-visual-action="Revisión de producto preparada">Revisar</button></div></td></tr>`}).join('')}</tbody></table></section>${products.length?'':empty('cc-products-management.svg','Sin productos reales.','La API no devolvió productos.')}`; bindFilters(main()); }
async function categoriesPage(){ const res=await safe('/categories'); const cats=res.data?.categories||[]; main().innerHTML=shell('Categorías','cc-categories.svg','Catálogo','Categorías reales administrables desde API.')+`<section class="cc-card mb-5"><h2 class="text-2xl font-bold">Crear categoría</h2><div id="categoryMsg"></div><form class="cc-form cc-form-grid" id="adminCategoryForm"><label class="cc-label">Nombre<input class="cc-input" name="nombre" required></label><label class="cc-label">Slug<input class="cc-input" name="slug" required></label><label class="cc-label full">Descripción<input class="cc-input" name="descripcion"></label><button class="cc-btn" type="submit">Crear categoría real</button></form></section>`+filters('categories',[['all','Todas'],['activa','Activas'],['inactiva','Inactivas']],'Buscar categoría')+`<section class="cc-grid cols-3">${cats.map(c=>`<article class="cc-card" data-admin-item="categories" data-status="${esc(norm(c.estado||'activa'))}" data-filter-text="${esc(`${c.nombre} ${c.slug} ${c.estado}`)}"><span class="cc-chip ${chipClass(c.estado||'activa')}">${esc(c.estado||'activa')}</span><h2>${esc(c.nombre)}</h2><p class="cc-muted">${esc(c.descripcion||'Sin descripción.')}</p><div class="cc-card-actions-row"><button class="cc-btn outline" type="button" data-category-edit="${esc(c.id)}">Editar visual</button><button class="cc-btn secondary" type="button" data-category-delete="${esc(c.id)}">Eliminar</button></div></article>`).join('')}</section>`; bindFilters(main()); document.querySelector('#adminCategoryForm')?.addEventListener('submit',async e=>{ e.preventDefault(); const body=Object.fromEntries(new FormData(e.currentTarget)); try{ const r=await postSafe('/categories',body); showMessage('#categoryMsg',r.message||'Categoría creada con API real.',true);}catch(error){showMessage('#categoryMsg',error.message);} }); }
function orderCard(o){ const st=norm(o.estado||o.estado_pago||'pendiente'); const id=o.id||o.pedido_id; return `<article class="cc-card" data-admin-item="orders" data-status="${esc(st)}" data-filter-text="${esc(JSON.stringify(o))}"><span class="cc-chip ${chipClass(st)}">${esc(st)}</span><h2>Pedido #${esc(id)}</h2><p class="cc-muted">Comprador: ${esc(o.comprador_nombre||o.buyer_name||'No disponible')} · Tienda: ${esc(o.tienda_nombre||'No disponible')}</p><p><b>Total:</b> ${money(o.total||0)} · <b>Fecha:</b> ${esc(o.created_at||o.fecha||'')}</p><div class="cc-card-actions-row"><a class="cc-btn outline" href="pedido-detalle.html?id=${esc(id)}">Ver detalle</a><button class="cc-btn" type="button" data-visual-action="Revisión de pedido preparada">Revisar</button></div></article>`; }
async function ordersPage(){ const res=await safe('/admin/orders'); const orders=res.data?.orders||[]; main().innerHTML=shell('Pedidos','cc-order-history.svg','Operación','Pedidos reales administrados.')+filters('orders',[['all','Todos'],['pendiente','Pendientes'],['pagado','Pagados'],['enviado','Enviados'],['entregado','Entregados'],['cancelado','Cancelados']],'Buscar pedido')+`<section class="cc-grid cols-2">${orders.map(orderCard).join('')}</section>${orders.length?'':empty('cc-order-history.svg','Sin pedidos reales.','La API no devolvió pedidos.')}`; bindFilters(main()); }
async function paymentsPage(){ const stats=(await safe('/admin/dashboard-stats')).data?.stats||{}; main().innerHTML=shell('Pagos','cc-payment-card.svg','Pagos','Listado administrativo de pagos pendiente en backend.')+filters('payments',[['all','Todos'],['aprobado','Aprobados'],['pendiente','Pendientes'],['rechazado','Rechazados'],['reembolsado','Reembolsados']],'Buscar pago')+`<section class="cc-grid cols-3"><article class="cc-card cc-metric-card"><b>Ventas pagadas</b><strong>${money(stats.ventas_totales||0)}</strong><span>Desde dashboard-stats</span></article><article class="cc-card cc-metric-card"><b>Comisiones</b><strong>${money(stats.comisiones_totales||0)}</strong><span>Resumen real</span></article></section>${empty('cc-payment-card.svg','Listado de pagos pendiente.','No existe GET /api/v1/payments ni GET /api/v1/admin/payments. El webhook simulado sí existe como acción administrativa.')}`; bindFilters(main()); }
async function shipmentsPage(){ const orders=(await safe('/admin/orders')).data?.orders||[]; main().innerHTML=shell('Envíos','cc-shipping-package.svg','Logística','Listado administrativo de envíos pendiente; se usa contexto de pedidos.')+filters('shipments',[['all','Todos'],['pendiente','Pendientes'],['enviado','Enviados'],['entregado','Entregados']],'Buscar envío')+`<section class="cc-grid cols-2">${orders.slice(0,8).map(o=>`<article class="cc-card" data-admin-item="shipments" data-status="${esc(norm(o.estado_envio||o.estado||'pendiente'))}" data-filter-text="${esc(JSON.stringify(o))}"><span class="cc-chip orange">${esc(o.estado_envio||'pendiente')}</span><h2>Pedido #${esc(o.id||o.pedido_id)}</h2><p class="cc-muted">Fuente: pedidos administrativos. Listado real de envíos pendiente.</p><button class="cc-btn outline" data-visual-action="Detalle de envío pendiente de backend" type="button">Ver detalle</button></article>`).join('')}</section>${empty('cc-shipping-package.svg','Endpoint de listado de envíos pendiente.','Existe PATCH /shipments/:id/status, pero no GET administrativo de envíos.')}`; bindFilters(main()); }
async function reviewsPage(){ const reports=(await safe('/admin/reports/products')).data?.reports||[]; main().innerHTML=shell('Reseñas y reportes','cc-rating-star-review.svg','Moderación','Moderación real de reseñas cuando hay id; listado directo pendiente.')+filters('reviews',[['all','Todas'],['pendiente','Pendientes'],['revisado','Aprobadas/Revisadas'],['rechazado','Ocultas/Rechazadas']],'Buscar reporte')+`<section class="cc-grid cols-2">${reports.map(r=>`<article class="cc-card" data-admin-item="reviews" data-status="${esc(norm(r.estado))}" data-filter-text="${esc(JSON.stringify(r))}"><span class="cc-chip ${chipClass(r.estado)}">${esc(r.estado)}</span><h2>${esc(r.producto_nombre||r.motivo||'Reporte de producto')}</h2><p class="cc-muted">${esc(r.descripcion||'Sin descripción.')}</p><div class="cc-card-actions-row"><button class="cc-btn" type="button" data-product-report="${esc(r.id)}" data-report-status="revisado">Marcar revisado</button><button class="cc-btn secondary" type="button" data-product-report="${esc(r.id)}" data-report-status="rechazado">Rechazar</button></div></article>`).join('')}</section>${reports.length?'':empty('cc-rating-star-review.svg','Sin reportes/reseñas reales.','No existe GET /admin/reviews; se muestran reportes de productos como fuente disponible.')}`; bindFilters(main()); }
async function commissionsPage(){ const stats=(await safe('/admin/dashboard-stats')).data?.stats||{}; main().innerHTML=shell('Comisiones','cc-commission.svg','Finanzas','Resumen real disponible desde estadísticas administrativas.')+filters('commissions',[['all','Mes actual'],['pendiente','Pendientes'],['pagada','Pagadas'],['revisada','Revisadas']],null)+`<section class="cc-grid cols-3"><article class="cc-card cc-metric-card"><b>Comisiones totales</b><strong>${money(stats.comisiones_totales||0)}</strong><span>API real</span></article><article class="cc-card cc-metric-card"><b>Ventas totales</b><strong>${money(stats.ventas_totales||0)}</strong><span>Pedidos pagados</span></article></section>${empty('cc-commission.svg','Listado de comisiones pendiente.','No existe GET /api/v1/admin/commissions ni PATCH de estado de comisión.')}`; }
async function notificationsPage(){ const [res,count]=await Promise.all([safe('/notifications'),safe('/notifications/unread-count')]); const nots=res.data?.notifications||[]; main().innerHTML=shell('Notificaciones','cc-notification-bell.svg','Alertas','Notificaciones reales del administrador.',`<button class="cc-btn" type="button" data-read-all>Marcar todas leídas (${count.data?.unread_count||0})</button>`)+filters('notifications',[['all','Todas'],['pedido','Pedidos'],['pago','Pagos'],['envio','Envíos'],['devolucion','Devoluciones'],['sistema','Sistema']],'Buscar notificación')+`<section class="cc-grid cols-2">${nots.map(n=>`<article class="cc-card" data-admin-item="notifications" data-status="${esc(norm(n.tipo||'sistema'))}" data-filter-text="${esc(`${n.titulo} ${n.mensaje} ${n.tipo}`)}"><span class="cc-chip ${n.leida?'neutral':'orange'}">${n.leida?'Leída':'No leída'}</span><h2>${esc(n.titulo)}</h2><p class="cc-muted">${esc(n.mensaje)}</p><small>${esc(n.created_at||'')}</small><div class="cc-card-actions-row"><button class="cc-btn outline" type="button" data-notification-read="${esc(n.id)}">Marcar leída</button><button class="cc-btn secondary" type="button" data-notification-delete="${esc(n.id)}">Eliminar</button></div></article>`).join('')}</section>${nots.length?'':empty('cc-notification-bell.svg','Sin notificaciones reales.','La API no devolvió notificaciones.')}`; bindFilters(main()); }
async function logsPage(){ const logs=(await safe('/admin/logs')).data?.logs||[]; main().innerHTML=shell('Logs','cc-audit-logs.svg','Auditoría','Logs reales del sistema.')+filters('logs',[['all','Todos'],['auth','Autenticación'],['producto','Productos'],['pedido','Pedidos'],['pago','Pagos'],['error','Errores']],'Buscar log')+`<section class="cc-table-wrap"><table class="cc-table"><thead><tr><th>Usuario</th><th>Acción</th><th>Módulo</th><th>Fecha</th><th>IP</th></tr></thead><tbody>${logs.map(l=>`<tr data-admin-item="logs" data-status="${esc(norm(l.entidad||l.modulo||'sistema'))}" data-filter-text="${esc(JSON.stringify(l))}"><td>${esc(l.usuario_nombre||l.usuario_id||'Sistema')}</td><td>${esc(l.accion)}</td><td>${esc(l.entidad||l.modulo||'')}</td><td>${esc(l.created_at||'')}</td><td>${esc(l.ip||'')}</td></tr>`).join('')}</tbody></table></section>${logs.length?'':empty('cc-audit-logs.svg','Sin logs reales.','La API no devolvió logs.')}`; bindFilters(main()); }
async function reportsPage(){ const [stats,pr,ur,ret,del,logs]=await Promise.all([safe('/admin/dashboard-stats'),safe('/admin/reports/products'),safe('/admin/reports/users'),safe('/admin/returns'),safe('/admin/account-delete-requests'),safe('/admin/logs')]); const s=stats.data?.stats||{}; main().innerHTML=shell('Reportes','cc-reports-analytics.svg','Reportes','Resumen real construido con endpoints administrativos.')+`<section class="cc-grid cols-4"><article class="cc-card cc-metric-card"><b>Usuarios activos</b><strong>${esc(s.total_usuarios_activos||0)}</strong><span>dashboard-stats</span></article><article class="cc-card cc-metric-card"><b>Productos</b><strong>${esc(s.total_productos||0)}</strong><span>dashboard-stats</span></article><article class="cc-card cc-metric-card"><b>Pedidos</b><strong>${esc(s.total_pedidos||0)}</strong><span>dashboard-stats</span></article><article class="cc-card cc-metric-card"><b>Ventas</b><strong>${money(s.ventas_totales||0)}</strong><span>pagadas</span></article></section><section class="cc-grid cols-3 mt-5"><article class="cc-card"><h2>Reportes de productos</h2><strong>${pr.data?.reports?.length||0}</strong></article><article class="cc-card"><h2>Reportes de usuarios</h2><strong>${ur.data?.reports?.length||0}</strong></article><article class="cc-card"><h2>Devoluciones</h2><strong>${ret.data?.returns?.length||0}</strong></article><article class="cc-card"><h2>Solicitudes de cuenta</h2><strong>${del.data?.requests?.length||0}</strong></article><article class="cc-card"><h2>Logs recientes</h2><strong>${logs.data?.logs?.length||0}</strong></article></section>`; }
function bindActions(){ document.addEventListener('click',async e=>{ const b=e.target.closest('button'); if(!b) return; try{ if(b.dataset.userStatus){ await patchSafe(`/admin/users/${b.dataset.userStatus}/status`,{estado:b.dataset.nextStatus}); b.textContent='Actualizado'; return; } if(b.dataset.storeAction){ await patchSafe(`/stores/${b.dataset.storeAction}/${b.dataset.action}`,{}); b.textContent='Actualizado'; return; } if(b.dataset.productVisibility){ await patchSafe(`/products/${b.dataset.productVisibility}/visibility`,{estado:b.dataset.nextStatus}); b.textContent='Actualizado'; return; } if(b.dataset.productReport){ await patchSafe(`/admin/reports/products/${b.dataset.productReport}`,{estado:b.dataset.reportStatus,respuesta_admin:'Revisado desde panel web.'}); b.textContent='Reporte actualizado'; return; } if(b.dataset.notificationRead){ await patchSafe(`/notifications/${b.dataset.notificationRead}/read`,{}); b.textContent='Leída'; return; } if(b.dataset.notificationDelete){ await delSafe(`/notifications/${b.dataset.notificationDelete}`); b.closest('.cc-card')?.remove(); return; } if(b.hasAttribute('data-read-all')){ await patchSafe('/notifications/read-all',{}); b.textContent='Todas marcadas'; return; } if(b.dataset.categoryDelete){ await delSafe(`/categories/${b.dataset.categoryDelete}`); b.closest('.cc-card')?.remove(); return; } if(b.dataset.categoryEdit){ b.textContent='Edición preparada'; return; } if(b.dataset.visualAction){ b.textContent=b.dataset.visualAction; return; } }catch(error){ b.textContent='Error API'; console.warn(error.message); } }); }
async function init(){ if(!adminPages.has(page)) return; const user=await adminSession(); if(!user) return; bindActions(); if(page==='admin.html') await dashboard(user); if(page==='admin-usuarios.html') await usersPage(); if(page==='admin-tiendas.html') await storesPage(); if(page==='admin-productos.html') await productsPage(); if(page==='admin-categorias.html') await categoriesPage(); if(page==='admin-pedidos.html') await ordersPage(); if(page==='admin-pagos.html') await paymentsPage(); if(page==='admin-envios.html') await shipmentsPage(); if(page==='admin-resenas.html') await reviewsPage(); if(page==='admin-comisiones.html') await commissionsPage(); if(page==='admin-notificaciones.html') await notificationsPage(); if(page==='admin-logs.html') await logsPage(); if(page==='admin-reportes.html') await reportsPage(); }
init();
