const model=require('../models/chat.model');
const notification=require('./notification.service');
const logService=require('./log.service');
function err(m,s){const e=new Error(m);e.statusCode=s;return e;}
function participates(c,userId){ return c && (Number(c.comprador_id)===Number(userId)||Number(c.vendedor_id)===Number(userId)); }
async function resolveConversationPayload(user,payload){ let comprador_id=payload.comprador_id||null, vendedor_id=payload.vendedor_id||null, tienda_id=payload.tienda_id||null, producto_id=payload.producto_id||null; if(producto_id){ const p=await model.findProduct(producto_id); if(!p) throw err('Producto no encontrado.',404); tienda_id=tienda_id||p.tienda_id; vendedor_id=vendedor_id||p.vendedor_id; } if(tienda_id && !vendedor_id){ const s=await model.findStore(tienda_id); if(!s) throw err('Tienda no encontrada.',404); vendedor_id=s.usuario_id; } if(user.rol==='comprador'){ comprador_id=user.id; if(!vendedor_id) throw err('Debe indicar vendedor, tienda o producto.',400); } else if(user.rol==='vendedor'){ vendedor_id=user.id; if(!comprador_id) throw err('El vendedor debe indicar comprador_id para iniciar conversación.',400); } else { if(!comprador_id||!vendedor_id) throw err('Administrador debe indicar comprador_id y vendedor_id.',400); } if(Number(comprador_id)===Number(vendedor_id)) throw err('No se puede crear conversación con el mismo usuario.',400); const comprador=await model.findUser(comprador_id); const vendedor=await model.findUser(vendedor_id); if(!comprador||!vendedor) throw err('Participante inactivo o no encontrado.',404); return {comprador_id,vendedor_id,tienda_id,producto_id}; }
async function createConversation(user,payload){ const data=await resolveConversationPayload(user,payload); const existing=await model.findExisting(data); if(existing) return await model.findConversation(existing.id); return model.createConversation(data); }
async function list(user){ return model.listForUser(user.id); }
async function messages(user,id,query){ const c=await model.findConversation(id); if(!participates(c,user.id)) throw err('Conversación no encontrada o sin permisos.',404); const limit=Math.min(Math.max(parseInt(query.limit||'50',10),1),100); const page=Math.max(parseInt(query.page||'1',10),1); return {conversation:c,messages:await model.messages(id,{limit,offset:(page-1)*limit}),pagination:{page,limit}}; }
async function sendMessage(user,id,payload,archivos=[],ip){ const c=await model.findConversation(id); if(!participates(c,user.id)) throw err('Conversación no encontrada o sin permisos.',404); const receptor_id=Number(c.comprador_id)===Number(user.id)?c.vendedor_id:c.comprador_id; const receptor=await model.findUser(receptor_id); if(!receptor) throw err('Receptor inactivo o no encontrado.',403); const contenido=String(payload.contenido ?? payload.mensaje ?? '').trim(); if(!contenido && !archivos.length) throw err('El mensaje debe incluir texto o archivo adjunto.',400); if(contenido.length>1000) throw err('El mensaje no puede superar 1000 caracteres.',400); const tipo=contenido&&archivos.length?'mixto':archivos.length?'archivo':'texto'; const conn=await model.pool.getConnection(); try{ await conn.beginTransaction(); const mid=await model.addMessage(conn,{conversacion_id:id,emisor_id:user.id,contenido,tipo,archivos}); await notification.create(conn,receptor_id,{tipo:'nuevo_mensaje',titulo:'Nuevo mensaje',mensaje:'Tienes un nuevo mensaje interno.',entidad_tipo:'conversaciones',entidad_id:id,url_destino:`/pages/conversation.html?id=${id}`}); await logService.log(conn,{usuario_id:user.id,accion:'mensaje_chat_enviado',entidad:'conversaciones',entidad_id:id,detalle:{mensaje_id:mid,tipo,archivos:archivos.length},ip}); await conn.commit(); const msgs=await model.messages(id,{limit:100,offset:0}); return msgs.find(m=>Number(m.id)===Number(mid))||{id:mid}; }catch(e){ await conn.rollback(); throw e; } finally{ conn.release(); } }
async function markRead(user,id){ const c=await model.findConversation(id); if(!participates(c,user.id)) throw err('Conversación no encontrada o sin permisos.',404); return {updated:await model.markRead(id,user.id)}; }
async function reportMessage(user,id,ip){ const m=await model.findMessage(id); if(!m || !participates(m,user.id)) throw err('Mensaje no encontrado o sin permisos.',404); const updated=await model.reportMessage(id); await logService.log(null,{usuario_id:user.id,accion:'mensaje_chat_reportado',entidad:'mensajes',entidad_id:id,detalle:{conversacion_id:m.conversacion_id},ip}); return updated; }
async function deleteMessage(user,id,ip){ const m=await model.findMessage(id); if(!m || !participates(m,user.id)) throw err('Mensaje no encontrado o sin permisos.',404); if(Number(m.emisor_id)!==Number(user.id) && user.rol!=='administrador') throw err('Solo el emisor o administrador puede eliminar el mensaje.',403); const updated=await model.deleteMessage(id); await logService.log(null,{usuario_id:user.id,accion:'mensaje_chat_eliminado',entidad:'mensajes',entidad_id:id,detalle:{conversacion_id:m.conversacion_id},ip}); return updated; }
module.exports={createConversation,list,messages,sendMessage,markRead,reportMessage,deleteMessage};
