const { pool }=require('../config/database');
const model=require('../models/userReport.model');
const notification=require('./notification.service');
const logService=require('./log.service');
const adminStats=require('../models/adminStats.model');
function err(m,s){const e=new Error(m);e.statusCode=s;return e;}
async function report(user,targetId,payload,ip){ const rid=Number(targetId); if(rid===Number(user.id)) throw err('No puede reportarse a sí mismo.',400); const target=await model.findUser(rid); if(!target) throw err('Usuario reportado no encontrado.',404); const dup=await model.duplicate(rid,user.id); if(dup) throw err('Ya existe un reporte pendiente o revisado hacia este usuario.',409); const conn=await pool.getConnection(); try{ await conn.beginTransaction(); const rep=await model.create({usuario_reportado_id:rid,usuario_reportante_id:user.id,motivo:payload.motivo,descripcion:payload.descripcion},conn); const [admins]=await conn.query(`SELECT u.id FROM usuarios u INNER JOIN roles r ON r.id=u.rol_id WHERE r.nombre='administrador' AND u.estado='activo'`); for(const a of admins){ await notification.create(conn,a.id,{tipo:'nuevo_reporte_usuario',titulo:'Nuevo reporte de usuario',mensaje:'Un usuario fue reportado.',entidad_tipo:'reportes_usuarios',entidad_id:rep.id,url_destino:'/pages/admin-reports-users.html'}); } await logService.log(conn,{usuario_id:user.id,accion:'usuario_reportado',entidad:'reportes_usuarios',entidad_id:rep.id,detalle:{usuario_reportado_id:rid},ip}); await conn.commit(); return rep; }catch(e){ await conn.rollback(); throw e; } finally{ conn.release(); } }
async function list(query){ const limit=Math.min(Math.max(parseInt(query.limit||'20',10),1),100); const page=Math.max(parseInt(query.page||'1',10),1); return {reports:await model.list({limit,offset:(page-1)*limit,estado:query.estado}),pagination:{page,limit}}; }
async function update(admin,id,payload,ip){ const rep=await model.findById(id); if(!rep) throw err('Reporte de usuario no encontrado.',404); const updated=await model.update(id,payload); if(payload.estado==='accionado' && payload.inactivar_usuario){ if(Number(rep.usuario_reportado_id)===Number(admin.id)) throw err('No puede inactivarse a sí mismo.',400); await adminStats.updateUserStatus(rep.usuario_reportado_id,'inactivo'); await notification.create(null,rep.usuario_reportado_id,{tipo:'usuario_inactivado',titulo:'Cuenta inactivada',mensaje:'Tu cuenta fue inactivada por revisión administrativa.',entidad_tipo:'usuarios',entidad_id:rep.usuario_reportado_id,url_destino:'/pages/account-settings.html'}); } if(rep.usuario_reportante_id){ await notification.create(null,rep.usuario_reportante_id,{tipo:'reporte_respondido',titulo:'Reporte revisado',mensaje:'Tu reporte de usuario fue actualizado.',entidad_tipo:'reportes_usuarios',entidad_id:id,url_destino:'/pages/notifications.html'}); } await logService.log(null,{usuario_id:admin.id,accion:'reporte_usuario_actualizado',entidad:'reportes_usuarios',entidad_id:id,detalle:{estado:payload.estado,inactivar_usuario:Boolean(payload.inactivar_usuario)},ip}); return updated; }
module.exports={report,list,update};
